### ISSUE TITLE
Cuando tienes master page te ahorras codigo

### ISSUE THREAD

**Issue by enelramon** [enelramon/FinanzasPersonalesWeb2016#1]
1. NO NECESITAN AGREGAR LA ETIQUETA  "< html > < / html> PORQUE YA ESTA EN LA MASTER PAGE
2. Les dije que trabajen con tabla o bootstrap

**Comment by chrisgenao** [comment]
Dijo solo con tabla, acabo de subir todo lo concerniente a mi proceso
